// Web hero illustrations for the two educational categories (2026-10-01):
// the seven "Tính thử trước khi quyết định" guides, the "Mua nhà bằng con số"
// collection page, and the collection's 23 articles. C05 and C11 keep their
// own approved images as their hero (content/loan-decision-ai-images.ts); they
// are not repeated here. Article text, charts and examples are unchanged.
//
// USER-APPROVED, 2026-10-01: AI-generated fictional people as WEB heroes for
// these surfaces only. Social posters/exports, news covers, the homepage and
// the tools keep their existing images; the seo-blog real-people rule for
// social packages is unchanged (content/tool-education-series.test.ts).
//
// Sources, both LOCAL artifacts (optional, never needed at runtime or in CI):
// - "library": the ten-image library, artifacts/ai-people-library-2026-10-01
//   (each made with a Pexels photo as composition reference only);
// - "supplement": per-article images generated by Codex,
//   artifacts/ai-web-heroes-2026-10-01/generated-supplement (prompt only, no
//   stock reference).
// The public files are plain sharp WebP resizes of the full 3:2 frame — no
// crop, no retouch, no upscale (1536 is the source width). Crops are CSS only:
// `focal` is the object-position for boxes wider than 3:2, and `mirror` flips
// the frame (no readable text in any of them).
//
// Not a photo by the reference's creator, not a customer, not an endorsement,
// and not a claim about any real place: image 09's lake has a small tower that
// resembles a real landmark; nothing on the page names or claims a location.

export const WEB_HERO_TAGLINE = "Ảnh minh họa AI";

export type WebHeroSource = { src: string; width: number; height: number };

export type EducationWebHero = {
  /**
   * "guide": a standalone tool guide's page hero and its thumbnails.
   * "article": a collection article's opening figure (after the short answer).
   */
  surface: "guide" | "collection" | "article";
  /** Post slug for a guide or article; the collection's own slug otherwise. */
  slug: string;
  /** Where the generated PNG lives in the local artifacts (see header). */
  origin: { set: "library"; n: number; file: string } | { set: "supplement"; id: string; file: string };
  /** SHA-256 of the generated PNG the WebP files were derived from. */
  generatedSha256: string;
  size: { w: number; h: number };
  /** 720 / 1200 / 1536 WebP, ascending. */
  sources: readonly [WebHeroSource, WebHeroSource, WebHeroSource];
  /** What is in frame only: no ethnicity, place, figure or relationship claim. */
  alt: string;
  /** CSS object-position for boxes wider than the 3:2 frame (keeps heads in). */
  focal: string;
  mirror: boolean;
  /**
   * The stock photo used ONLY as a composition reference — not the output's
   * author. `null` for supplement images, generated from a prompt alone.
   */
  compositionReference: { pexelsId: string; url: string; creator: string } | null;
  approvedOn: string;
};

const sources = (base: string) => {
  return [
    { src: `${base}-720.webp`, width: 720, height: 480 },
    { src: `${base}-1200.webp`, width: 1200, height: 800 },
    { src: `${base}-1536.webp`, width: 1536, height: 1024 },
  ] as const;
};

const hero = (
  surface: EducationWebHero["surface"],
  slug: string,
  n: number,
  name: string,
  generatedSha256: string,
  compositionReference: EducationWebHero["compositionReference"],
  alt: string,
  focal: string,
  mirror = false,
): EducationWebHero => ({
  surface,
  slug,
  origin: { set: "library", n, file: `images/${String(n).padStart(2, "0")}-${name}.png` },
  generatedSha256,
  size: { w: 1536, h: 1024 },
  sources: sources(`/images/education/ai-library-${String(n).padStart(2, "0")}-${name}`),
  alt: `${WEB_HERO_TAGLINE}: ${alt}`,
  focal,
  mirror,
  compositionReference,
  approvedOn: "2026-10-01",
});

const ref = (pexelsId: string, slug: string, creator: string) => ({
  pexelsId,
  url: `https://www.pexels.com/photo/${slug}-${pexelsId}/`,
  creator,
});

export const EDUCATION_WEB_HEROES: readonly EducationWebHero[] = [
  hero(
    "collection", "mua-nha-bang-con-so", 3, "first-home-conversation",
    "585dddb87d67cf224ff268d21853b3b5680facbcbef327b2639b1a69f34d68e6",
    ref("7417519", "a-couple-having-a-conversation-while-sitting-on-a-couch", "cottonbro studio"),
    "một người phụ nữ và một người đàn ông ngồi trên ghế sofa màu kem trong phòng khách nhiều nắng, quay sang trò chuyện với nhau",
    "50% 30%",
    // Mirrored so both faces clear the desktop green ramp (see collection-hero.tsx).
    true,
  ),
  hero(
    "guide", "vay-mua-xe-con-du-bao-nhieu", 4, "weekend-car-plan",
    "d7fcfdf33bf5b9ae89124645045814c12be3b2b6f3a1303c49fb0fc419663d97",
    ref("7671364", "man-and-a-woman-sitting-on-sofa-while-looking-at-the-screen-of-a-laptop", "Ivan S"),
    "một người phụ nữ và một người đàn ông đứng cạnh một chiếc ô tô màu bạc đang đỗ, cùng xem máy tính bảng và mỉm cười",
    "50% 15%",
  ),
  hero(
    "guide", "lai-tu-7-len-9-tang-2-hay-28-phan-tram", 5, "monthly-budget",
    "3ab49de870c931cae90c329c6e9d93a7d01249db9f300712357370919cf09d9a",
    ref("8297072", "a-woman-using-calculator", "Mikhail Nilov"),
    "một người phụ nữ ngồi bên bàn gỗ cạnh cửa sổ, một tay ghi vào sổ, một tay bấm máy tính cầm tay, bên cạnh là laptop và cốc nước",
    "50% 20%",
  ),
  hero(
    "guide", "lai-kep-bao-nhieu-la-tien-ban-tu-gop", 6, "long-term-growth",
    "b44e49523e812f3e5332c4635568a2891c8dd21384638025b8e136e45465de4e",
    ref("7490459", "a-man-using-a-laptop", "Kampus Production"),
    "một người đàn ông ngồi bên bàn gỗ cạnh cửa sổ lớn, gõ phím laptop và mỉm cười nhẹ",
    "50% 20%",
  ),
  hero(
    "guide", "can-tien-truoc-dao-han-mat-bao-nhieu-lai", 7, "quiet-savings",
    "f2b447601d9c342c03b509b44effaa22976e601c207581ea6cd095c4a85fc0c1",
    ref("6545334", "a-woman-using-her-laptop", "Tima Miroshnichenko"),
    "một người phụ nữ ngồi bên bàn gỗ tròn, nhìn màn hình laptop và mỉm cười, cạnh một chén trà",
    "50% 25%",
  ),
  hero(
    "guide", "giam-20-roi-giam-10-co-phai-giam-30", 8, "savings-goal-notebook",
    "a47d988a524368e5ec20b52859852419cbe0370e091dfbb6563650df8e242ba1",
    ref("5154348", "concentrated-asian-woman-using-laptop-and-writing-in-notebook", "Budgeron Bach"),
    "một người phụ nữ ngồi trên đệm cạnh bàn gỗ thấp, vừa ghi vào cuốn sổ vừa nhìn laptop",
    "50% 10%",
  ),
  hero(
    "guide", "de-danh-huu-tri-tien-du-den-bao-nhieu-tuoi", 9, "active-future-outdoors",
    "aea11edc92b780e9663f0ba3a1c75819e56ced882b5353096980930d00fd5696",
    ref("7937885", "an-elderly-couple-smiling-at-the-camera", "Rhea Jabagat"),
    "một người đàn ông và một người phụ nữ đi bộ trên lối đi lát gạch ven hồ, hai bên nhiều cây xanh, vừa đi vừa trò chuyện",
    "50% 10%",
  ),
  hero(
    "guide", "cong-40-vao-gia-von-co-phai-lai-40", 10, "small-business-planning",
    "a55c4a11da87beaa6296893b05f15863a4f759e21803c84ce53a366d3dcf8626",
    ref("5410107", "cheerful-asian-woman-working-in-floral-shop", "Amina Filkins"),
    "một người phụ nữ đeo tạp dề ngồi bên quầy gỗ giữa nhiều chậu hoa và cây xanh, đang viết vào cuốn sổ",
    "50% 30%",
  ),
];

/** A collection article's hero from the generated supplement (no stock reference). */
const article = (
  planId: string,
  slug: string,
  generatedSha256: string,
  alt: string,
  /** "clean": Codex's logo-free edit replaces the original (manifest-logo-cleanup.json). */
  variant: "original" | "clean" = "original",
): EducationWebHero => ({
  surface: "article",
  slug,
  origin: { set: "supplement", id: planId, file: `${planId.toLowerCase()}-hero-${variant}.png` },
  generatedSha256,
  size: { w: 1536, h: 1024 },
  sources: sources(`/images/education/hero-${planId.toLowerCase()}`),
  alt: `${WEB_HERO_TAGLINE}: ${alt}`,
  focal: "50% 30%",
  mirror: false,
  compositionReference: null,
  approvedOn: "2026-10-01",
});

/**
 * Collection articles with their hero, keyed by plan id. C05 and C11 are not
 * listed: their approved illustration already opens the article.
 */
export const ARTICLE_WEB_HEROES: readonly EducationWebHero[] = [
  article("C01", "co-600-trieu-nen-tim-nha-tam-gia-nao", "1fa67860b3f79aa813d98228249029fb65a8172a94ccc6fbc5ae3984eef977ff",
    "một người đàn ông và một người phụ nữ đứng trong căn hộ nhiều nắng, cùng xem một cuốn tài liệu có sơ đồ mặt bằng"),
  article("C02", "vay-2-ty-moi-thang-tra-bao-nhieu", "c751b765d55fdd494679860a6a55e381a26dc8f93ab68db0b56fbf2a8c4d265b",
    "một người phụ nữ cầm cuốn sổ và một người đàn ông bấm máy tính cầm tay bên bàn gỗ tròn có giấy tờ và laptop"),
  article("C03", "het-uu-dai-khoan-tra-tang-bao-nhieu", "15a0b28b249d9b9981b1afc5a57cd936f1b513f846cf01b7ad3bc2387ba0e43f",
    "một người phụ nữ đang nói và một người đàn ông chăm chú lắng nghe bên bàn có lịch để bàn, sổ ghi chép và laptop"),
  article("C04", "du-tien-tra-truoc-sau-3-nam", "1027eec44c0b1c5fd89eb9a055877df3bc54bca71609657778544b819038a0b9",
    "một người phụ nữ mỉm cười ghi vào cuốn sổ, người đàn ông ngồi cạnh cầm cốc nhìn sang, bên bàn gỗ trong phòng khách nhiều nắng"),
  article("C06", "duoc-vay-khong-co-nghia-nen-vay-het", "9f56afad041340555a470f235926d5225765dd48f16b964df9f588b6b009cbd3",
    "một người phụ nữ chỉ vào một trong ba tập hồ sơ trên mặt bàn đá, người đàn ông cầm một tờ giấy và suy nghĩ, bên cạnh là laptop"),
  article("C07", "vay-20-nam-hay-25-nam", "b682d67e76f7bd22eb1ff74bf9e317d134a3f1f5da535ee3df94093499c1a101",
    "một người đàn ông và một người phụ nữ ôm cuốn sổ đứng trên ban công nhiều cây xanh, nhìn ra khu phố lúc nắng sớm"),
  article("C08", "tiep-tuc-thue-hay-mua-nha", "87568c256c58fad11d4c9ba9a58f57b3f5b2e0d28cb91704b3c593cf766633c7",
    "một người phụ nữ cầm máy tính bảng và một người đàn ông đứng trong căn phòng trống có thùng các-tông, nhìn quanh căn phòng"),
  article("C09", "gop-them-2-trieu-dat-muc-tieu-som-bao-lau", "2fbd58a23be31ee72783afac38ad2aafc30555b3fa9b80ed5e72c029c7c18ad7",
    "một người đàn ông ngồi bên bàn gỗ cạnh cửa sổ, viết vào cuốn sổ, bên cạnh là laptop và cốc nước", "clean"),
  article("C10", "co-tien-du-tra-them-no-giam-bao-nhieu-lai", "3c1bf72d426fe8df8ae71d6a88cc3a4c2e0f7f46b36345fb189e5204832c8492",
    "một người phụ nữ và một người đàn ông ngồi trên ghế sofa trong phòng khách lúc chiều tối, cùng xem máy tính bảng", "clean"),
  article("C12", "doi-sang-khoan-vay-lai-thap-hon-khi-nao-bu-duoc-chi-phi", "8600bba4d3b2601e3c5c56f15bc2d70f72d34b8f69c5b2f9ea9f26fcb1262292",
    "một người phụ nữ và một người đàn ông ngồi ở bàn tròn trong quán cà phê, mỗi người cầm một tập tài liệu và cân nhắc"),
  article("C13", "lai-suat-quang-cao-va-chi-phi-vay-that", "3daa8fe4bc8ba934b7f43c3fe40d8e1a15d43383b5a9169c830804f7539c2d83",
    "một người phụ nữ đeo kính ngồi bên bàn làm việc, đọc kỹ một tờ giấy và chỉ tay vào cuốn sổ, cạnh laptop"),
  article("C14", "het-an-han-goc-khoan-tra-tang-bao-nhieu", "3420de0d25fb950b68cc08d405b89002ebbd5f42b7a42cf981f68a1ec19a5875",
    "một người đàn ông cầm bút ghi vào sổ, một người phụ nữ chỉ vào tờ lịch trên bàn ăn sáng, cả hai mỉm cười"),
  article("C15", "tra-5-nam-no-giam-bao-nhieu", "686dbda0e9f36e9bb748cfd24b98a4f6603bc63cc695cb75a20b1179b573594c",
    "một người đàn ông ngồi ở bàn gỗ ngoài ban công nhiều cây xanh, cầm bút và đọc cuốn sổ, cạnh một laptop đóng"),
  article("C16", "thu-nhap-bao-nhieu-thi-mua-duoc-nha-o-xa-hoi", "a2a3379d009523a6279f3166fdc725365107a07e06ca77c0a722b6474f79010b",
    "một người phụ nữ cầm cuốn sổ và một người đàn ông đi bộ trên lối đi giữa khu vườn của một khu căn hộ, vừa đi vừa trò chuyện"),
  article("C17", "thu-nhap-30-trieu-mua-nha-duoc-khong", "8b2a70f1e886c1ac17bde96ac9a3757caea22160973f011a58d74c3aa21b63d4",
    "một người phụ nữ cầm cốc và một người đàn ông đứng cạnh cửa kính lớn của một căn hộ, cùng nhìn ra ngoài và mỉm cười"),
  article("C18", "mua-can-ho-2-ty-can-bao-nhieu-tien-mat", "e6b1cbfaecdcaf390e09028b6fe51ec18882aea9f329d96dbcd322b51ef74385",
    "một người phụ nữ ghi vào sổ bên máy tính cầm tay, người đàn ông cầm cốc ngồi cạnh nhìn theo, phía sau là các thùng các-tông"),
  article("C19", "o-chung-cu-ton-them-bao-nhieu-moi-thang", "55725315fc4fac7faa62c895dc502d817f523bf3bd203a925f9b1260993a0098",
    "một người phụ nữ ngồi bên quầy bếp đọc một tờ giấy giữa vài phong bì, phía sau một người đàn ông đang tưới cây"),
  article("C20", "thu-nhap-30-trieu-con-thieu-bao-nhieu-von", "8488c0ea6c26a3be06513f82a256a31272b5944f3ba13b0897cafe7761a12c45",
    "một người phụ nữ ngồi trên thảm xem hai phong bì, người đàn ông ngồi trên ghế sofa phía sau chống cằm suy nghĩ"),
  article("C21", "vay-870-trieu-lai-uu-dai-tra-the-nao", "153ecc3f24085f5c5ace8e7bf03e622ea2a3b6e174ef2098635ace33dfe9cbaa",
    "một người đàn ông và một người phụ nữ cầm bình nước, vừa đi bộ trên lối đi rợp cây vừa trò chuyện và mỉm cười"),
  article("C22", "hai-chuong-trinh-vay-ho-30-trieu-chon-nao", "c1b8ad9be65cbe2832e10675a479977c0435ef869caa807c6d9c711666be500f",
    "một người phụ nữ và một người đàn ông ngồi bên bàn gỗ, mỗi người cầm một tập hồ sơ màu khác nhau và cân nhắc"),
  article("C23", "ho-30-trieu-het-uu-dai-co-con-tra-duoc", "334774a089ba9bf601148ab55643cc2df3633d1f4e98eacc69783823c261d9e0",
    "một người phụ nữ ghi vào sổ trên quầy bếp, người đàn ông ngồi cạnh chống cằm nhìn theo, bên cạnh là laptop đóng"),
];

/**
 * Collection articles whose supplement image is not generated yet. Kept
 * honest by content/education-web-heroes.test.ts: an id leaves this list in
 * the same change that adds its entry above; until then the article renders
 * exactly as before, with no placeholder. Empty since all 21 were supplied.
 */
export const PENDING_ARTICLE_HEROES: readonly string[] = [];

/** Every hero surface: guides, the collection page and the articles. */
export const ALL_WEB_HEROES: readonly EducationWebHero[] = [...EDUCATION_WEB_HEROES, ...ARTICLE_WEB_HEROES];

/** A collection article's hero, if it has one (C05/C11 use their illustration). */
export function articleHero(slug: string): EducationWebHero | undefined {
  return ARTICLE_WEB_HEROES.find((h) => h.slug === slug);
}

/** The page hero of a standalone tool guide, if it has one. */
export function guideHero(slug: string): EducationWebHero | undefined {
  return EDUCATION_WEB_HEROES.find((h) => h.surface === "guide" && h.slug === slug);
}

export function collectionHero(): EducationWebHero {
  const h = EDUCATION_WEB_HEROES.find((x) => x.surface === "collection");
  if (!h) throw new Error("content/education-web-heroes.ts: no collection hero");
  return h;
}

export function webHeroSrcSet(h: EducationWebHero): string {
  return h.sources.map((s) => `${s.src} ${s.width}w`).join(", ");
}
