/**
 * The 2026-09-30 tool education series — ten tools, one canonical article and
 * one social package each. See content/tool-education-series.ts and
 * docs/tool-education-series-2026-09-30.md.
 *
 * Every quoted figure is recomputed here from the production engine or view
 * helper on the declared example, and every exercise names buttons the tool
 * ships (read from the tool's own copy constants).
 *
 * WHAT IT CANNOT: appearance, rendered fonts, or a real click in a browser.
 * Exported PNGs are required by the `PENDING_EXPORTS` gate below.
 */
import { describe, expect, it, vi } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";

vi.mock("next/navigation", () => ({
  usePathname: () => "/blog/",
  useSearchParams: () => new URLSearchParams(),
  notFound: () => {
    throw new Error("notFound");
  },
}));

import {
  LOAN_DECISION_PENDING_EXPORTS,
  LOAN_DECISION_SERIES,
  PENDING_EXPORTS,
  TOOL_EDUCATION_SERIES,
} from "@/content/tool-education-series";
import { POSTS, getPost, postKind } from "@/content/posts";
import { getEducationArticle } from "@/content/education/articles";
import { getCalculator } from "@/content/calculators/registry";
import { TOOL_NEXT_STEPS } from "@/content/calculators/next-steps";
import { TOOL_SHELL } from "@/content/calculators/tool-shell";
import { computeCompound } from "@/lib/calc/compound";
import { computeTermDeposit } from "@/lib/calc/term-deposit";
import { computePercent } from "@/lib/calc/percent";
import { adjustPrice } from "@/lib/calc/price-adjust";
import { computeMargin } from "@/lib/calc/margin";
import { resolveLongTermPlan } from "@/lib/calc/long-term-plan";
import { retirementStatus } from "@/lib/calc/retirement-status";
import { readRoutePlan } from "@/components/retirement-plan-read";
import { targetView } from "@/components/retirement-plan-target-view";
import { compoundTrialLabel } from "@/components/compound-learning";
import { trialLabel, visibleTrialKeys } from "@/components/deposit-learning";
import { nextPercentValue, percentFormState } from "@/components/percent-learning";
import { nextPriceValue, priceAdjustFormState } from "@/components/price-adjust-learning";
import { marginFormState, marginTrialKeys, nextMarginValue } from "@/components/margin-learning";
import { COMPOUND } from "@/content/calculators/compound";
import { COMPOUND_LEARNING } from "@/content/calculators/compound-learning";
import { TERM_DEPOSIT } from "@/content/calculators/term-deposit";
import { DEPOSIT_LEARNING } from "@/content/calculators/deposit-learning";
import { RETIREMENT_PLAN } from "@/content/calculators/retirement-plan";
import { PERCENT } from "@/content/calculators/percent";
import { PERCENT_LEARNING } from "@/content/calculators/percent-learning";
import { PRICE_ADJUST } from "@/content/calculators/price-adjust";
import { PRICE_ADJUST_LEARNING } from "@/content/calculators/price-adjust-learning";
import { MARGIN } from "@/content/calculators/margin";
import { MARGIN_LEARNING } from "@/content/calculators/margin-learning";
import { ARITH_WORDS } from "@/content/calculators/arith-learning-words";

const read = (path: string) => readFileSync(path, "utf8");

/**
 * The only people photos approved for the series (researched 2026-09-30; the
 * source page's own metadata identifies the subjects as Asian). Files are the
 * unmodified originals. 6818113 is excluded by the user; AI25.Studio 8374288
 * and 8374269 are labelled AI-generated by their account and are not people.
 */
const photo = (name: string, slug: string, id: string, w: number, h: number) => ({
  name,
  url: `https://www.pexels.com/photo/${slug}-${id}/`,
  file: `public/images/people/pexels-${id}-original.jpg`,
  size: { w, h },
});
// One DISTINCT source photograph per topic (user correction, 2026-09-30):
// 7593053 is the released car package's photo and is not reused here.
const PHOTOS = {
  "7937885": photo("Rhea Jabagat", "an-elderly-couple-smiling-at-the-camera", "7937885", 3456, 5184),
  "5410107": photo("Amina Filkins", "cheerful-asian-woman-working-in-floral-shop", "5410107", 6000, 4000),
  "5710149": photo("Sam Lion", "positive-asian-woman-choosing-goods-in-vintage-boutique", "5710149", 3744, 5616),
  "7417519": photo("cottonbro studio", "a-couple-having-a-conversation-while-sitting-on-a-couch", "7417519", 6450, 4300),
  "7671364": photo("Ivan S", "man-and-a-woman-sitting-on-sofa-while-looking-at-the-screen-of-a-laptop", "7671364", 6720, 4480),
  "8297072": photo("Mikhail Nilov", "a-woman-using-calculator", "8297072", 6000, 4000),
  "7490459": photo("Kampus Production", "a-man-using-a-laptop", "7490459", 6016, 4016),
  "6545334": photo("Tima Miroshnichenko", "a-woman-using-her-laptop", "6545334", 2477, 3715),
  "5154348": photo("Budgeron Bach", "concentrated-asian-woman-using-laptop-and-writing-in-notebook", "5154348", 2624, 3936),
  "6538435": photo("cottonbro studio", "a-woman-sitting-at-the-table", "6538435", 3837, 5756),
} as const;
const HERO_PHOTO: Record<string, keyof typeof PHOTOS> = {
  "ke-hoach-huu-tri": "7937885",
  "lai-kep": "7490459",
  "muc-tieu-tiet-kiem": "5154348",
  "tien-gui-co-ky-han": "6545334",
  "kha-nang-mua-nha": "7417519",
  "vay-mua-nha": "7671364",
  "lai-suat-tha-noi": "8297072",
  "tinh-phan-tram": "6538435",
  "giam-gia-va-thue": "5710149",
  "margin-va-markup": "5410107",
};
/** Photos mirrored in their poster: only where the frame has no readable text. */
const MIRRORED = new Set<keyof typeof PHOTOS>(["7417519"]);
const vnd = (n: number) => `${Math.round(n).toLocaleString("vi-VN")} ₫`;
const pct = (n: number) => n.toFixed(2).replace(".", ",");
const SITE = "https://www.finhome.group";
const body = (slug: string) => read(`content/posts/${slug}.md`);
const entry = (tool: string) => TOOL_EDUCATION_SERIES.find((e) => e.tool === tool)!;
const pkg = (tool: string) => ({ html: read(`public/social/${tool}/index.html`), caption: read(`public/social/${tool}/caption.md`) });
/** The Markdown exercise section of a guide. */
const exercise = (slug: string) => {
  const b = body(slug);
  return b.slice(b.indexOf("## Tự thử trong vài phút"), b.indexOf("## Đối chiếu"));
};
/** A shipped button or label, quoted in bold as the guides name them. */
const named = (label: string) => `**“${label}”**`;

describe("the series covers exactly the ten requested tools", () => {
  it("maps each tool once to one canonical article, with no duplicate slugs", () => {
    expect(TOOL_EDUCATION_SERIES.map((e) => e.tool)).toEqual([
      "ke-hoach-huu-tri", "lai-kep", "muc-tieu-tiet-kiem", "tien-gui-co-ky-han", "kha-nang-mua-nha",
      "vay-mua-nha", "lai-suat-tha-noi", "tinh-phan-tram", "giam-gia-va-thue", "margin-va-markup",
    ]);
    expect(new Set(TOOL_EDUCATION_SERIES.map((e) => e.article)).size).toBe(10);
    const slugs = POSTS.map((p) => p.slug);
    expect(new Set(slugs).size).toBe(slugs.length);
  });

  it("points at live tools and real articles — reused where one already teaches the tool", () => {
    for (const e of TOOL_EDUCATION_SERIES) {
      expect(getCalculator(e.tool)?.status, e.tool).toBe("live");
      expect(existsSync(`app/cong-cu/${e.tool}/page.tsx`), e.tool).toBe(true);
      const post = getPost(e.article);
      expect(post, e.article).toBeDefined();
      if (e.kind === "reuse") {
        expect(postKind(post!)).toBe("education");
        expect(getEducationArticle(e.article)?.exercise.toolSlug, e.article).toBe(e.tool);
        expect(e.exports).toEqual([]);
      } else {
        expect(postKind(post!)).toBe("guide");
        expect(existsSync(`content/posts/${e.article}.md`), e.article).toBe(true);
        expect(post!.topics).toEqual([]);
        expect(post!.excerpt.length, e.article).toBeGreaterThanOrEqual(120);
        expect(post!.excerpt.length, e.article).toBeLessThanOrEqual(160);
        expect(post!.cover).toBe(`/images/blog/${e.article}-cover.png`);
      }
    }
    expect(TOOL_EDUCATION_SERIES.filter((e) => e.kind === "reuse").map((e) => e.tool)).toEqual([
      "muc-tieu-tiet-kiem", "kha-nang-mua-nha", "vay-mua-nha", "lai-suat-tha-noi",
    ]);
  });
});

describe("the journey: poster → article → Tính với số của tôi → tool → article again", () => {
  const guides = TOOL_EDUCATION_SERIES.filter((e) => e.kind === "new");

  it("gives every new guide an early and an ending CTA to its tool's unchanged default route", () => {
    for (const e of guides) {
      const b = body(e.article);
      const cta = `[Tính với số của tôi →](/cong-cu/${e.tool}/)`;
      expect(getPost(e.article)!.headerCta).toEqual({ label: "Tính với số của tôi", href: `/cong-cu/${e.tool}/` });
      expect(b.indexOf(cta), e.article).toBeGreaterThan(-1);
      expect(b.indexOf(cta), e.article).toBeLessThan(b.indexOf("\n## "));
      expect(b.lastIndexOf(cta), e.article).toBeGreaterThan(b.indexOf("## Đối chiếu trước khi quyết định"));
      expect(b.lastIndexOf(cta), e.article).toBeLessThan(b.indexOf("## Nguồn để đọc thêm"));
      // No figure or personal field travels in a link.
      for (const [, link] of b.matchAll(/\]\((\/cong-cu\/[^)]+)\)/g)) expect(link, link).not.toMatch(/[?#=&]/);
      expect(b, e.article).not.toMatch(/^# /m);
      // The example is declared as such. The storage sentence is the narrow,
      // verifiable one (review-1 item 4): no claim about what is never sent.
      expect(b, e.article).toMatch(/giả định/);
      expect(b, e.article).toContain("Phép tính chạy ngay trên trình duyệt; công cụ không tự lưu lại kế hoạch khi tải lại trang.");
      expect(b, e.article).not.toContain("không gửi đi số bạn nhập");
    }
  });

  it("keeps every internal destination real; pending images are the declared exports", () => {
    for (const e of guides) {
      for (const [, target] of body(e.article).matchAll(/\]\((\/[^)]+)\)/g)) {
        if (target.startsWith("/images/")) {
          const file = `public${target}`;
          const declared = e.exports.some((x) => x.file === file);
          expect(declared || existsSync(file), target).toBe(true);
        } else if (target.startsWith("/blog/")) {
          expect(getPost(target.replace(/^\/blog\/|\/$/g, "")), target).toBeDefined();
        } else {
          expect(existsSync(`app${target}page.tsx`), target).toBe(true);
        }
      }
      expect(body(e.article)).toContain(`](/images/blog/${e.article}-flow.png)`);
    }
  });

  it("links every tool back to its canonical article, in a labelled new tab", () => {
    for (const e of TOOL_EDUCATION_SERIES) {
      const href = `/blog/${e.article}/`;
      const seam = TOOL_NEXT_STEPS[e.tool]?.education?.href;
      if (seam !== undefined) {
        expect(seam, e.tool).toBe(href);
        continue;
      }
      // The three tools without a next-steps block render the shared EducationLink.
      const content = { "ke-hoach-huu-tri": RETIREMENT_PLAN, "giam-gia-va-thue": PRICE_ADJUST, "margin-va-markup": MARGIN }[e.tool];
      expect(content, e.tool).toBeDefined();
      expect(content!.guideLink.href, e.tool).toBe(href);
      const route = read(`app/cong-cu/${e.tool}/page.tsx`);
      expect(route, e.tool).toContain("<EducationLink href={C.guideLink.href}");
    }
    expect(TOOL_SHELL.nextSteps.newTabNote).toMatch(/tab mới/);
  });

  it("makes every new guide discoverable on /blog/", async () => {
    const html = renderToStaticMarkup(createElement((await import("@/app/blog/page")).default));
    for (const e of guides) expect(html, e.article).toMatch(new RegExp(`href="/blog/${e.article}/?"`));
  }, 120_000);
});

describe("new guides quote the engine on the tool's own shipped example", () => {
  it("lãi kép: 100 triệu + 8 triệu/tháng, 6%/năm, 10 năm", () => {
    const a = "lai-kep-bao-nhieu-la-tien-ban-tu-gop";
    const f = COMPOUND.form;
    expect([f.defaultPrincipal, f.defaultContribution, f.defaultRate, f.defaultYears, f.defaultCompounding]).toEqual(["100.000.000", "8.000.000", "6", "10", "monthly"]);
    const base = computeCompound({ principal: 100e6, annualRatePercent: 6, years: 10, compounding: "monthly", contributionPerPeriod: 8e6 })!;
    const more = computeCompound({ principal: 100e6, annualRatePercent: 6, years: 10, compounding: "monthly", contributionPerPeriod: 9e6 })!;
    const y5 = base.yearlyBalances.find((y) => y.year === 5)!;
    for (const n of [base.futureValue, base.totalContributed, base.totalInterest, y5.balance, y5.interest, more.futureValue, more.totalContributed, more.totalInterest]) {
      expect(body(a)).toContain(vnd(n));
    }
    expect(Math.round((base.totalInterest / base.futureValue) * 100)).toBe(29);
    expect(((more.futureValue - base.futureValue) / 1e6).toFixed(1)).toBe("163.9");
    expect(computeCompound({ principal: 100e6, annualRatePercent: 0, years: 10, compounding: "monthly", contributionPerPeriod: 8e6 })!.futureValue).toBe(1.06e9);
    const ex = exercise(a);
    for (const label of [TOOL_SHELL.cta.label, COMPOUND_LEARNING.title, COMPOUND_LEARNING.steps.next.short, compoundTrialLabel("monthly"), COMPOUND_LEARNING.undo]) {
      expect(ex, label).toContain(named(label));
    }
    expect(compoundTrialLabel("monthly")).toBe("Gửi thêm 1 triệu mỗi tháng");
    // The timeline opens at its END (year 10), where "Sau ›" is disabled, so the
    // exercise must send the reader to the beginning first (browser finding).
    const first = COMPOUND_LEARNING.steps.first.short;
    const next = COMPOUND_LEARNING.steps.next.short;
    expect(first).toBe("« Đầu");
    expect(COMPOUND_LEARNING.steps.first.name).toBe("Về lúc bắt đầu");
    expect(ex).toContain(named(first));
    expect(ex.indexOf(named(first))).toBeLessThan(ex.indexOf(named(next)));
    expect(ex.slice(0, ex.indexOf(named(first)))).not.toContain(named(next));
    expect(((base.yearlyBalances.find((y) => y.year === 1)!.balance) / 1e6).toFixed(1)).toBe("204.9");
    expect(ex).toContain("năm 1 khoảng 204,9 triệu");
    const { html, caption } = pkg("lai-kep");
    for (const s of ["1,49 tỷ", "1,06 tỷ", "433 triệu"]) { expect(html).toContain(s); expect(caption).toContain(s); }
  });

  it("tiền gửi: 500 triệu, 12 tháng, 5,5%/năm, rút ở tháng 9 với 0,2%/năm", () => {
    const a = "can-tien-truoc-dao-han-mat-bao-nhieu-lai";
    const f = TERM_DEPOSIT.form;
    expect([f.defaultMode, f.defaultPrincipal, f.defaultRate, f.defaultTerm, f.defaultPayout, f.defaultCycles, f.defaultDemandRate, f.defaultBreak]).toEqual(["term", "500.000.000", "5,5", "12", "maturity", "1", "0,2", "9"]);
    const input = { principal: 500e6, annualRatePercent: 5.5, termMonths: 12, payout: "maturity" as const, cycles: 1, compoundOnRollover: true, demandRatePercent: 0.2 };
    const at9 = computeTermDeposit({ ...input, breakAfterMonths: 9 })!;
    const at12 = computeTermDeposit({ ...input, breakAfterMonths: 12 })!;
    const at11 = computeTermDeposit({ ...input, breakAfterMonths: 11 })!;
    for (const n of [at9.totalInterest, at9.earlyInterest!, at9.earlyForegoneInterest!, at9.earlyLoss!]) expect(body(a)).toContain(vnd(n));
    expect(at9.earlyLoss).toBe(19_875_000);
    expect(at12.earlyInterest).toBe(27_500_000);
    expect(at12.earlyLoss).toBe(0);
    expect(at11.earlyLoss! / at11.earlyForegoneInterest!).toBeGreaterThan(0.95);
    // The buttons the default actually renders — one cycle hides "đúng đáo hạn đầu".
    const ctx = { termMonths: 12, cycles: 1, start: null };
    const shown = visibleTrialKeys("term", ctx).map((k) => trialLabel(k, ctx));
    expect(shown).toEqual(["Rút trước đáo hạn đầu 1 tháng (tháng 11)", "Rút khi hết kế hoạch (tháng 12)"]);
    const ex = exercise(a);
    for (const label of [TOOL_SHELL.cta.label, DEPOSIT_LEARNING.title, ...shown, DEPOSIT_LEARNING.undo]) expect(ex, label).toContain(named(label));
    expect(body(a)).not.toContain("Rút đúng đáo hạn đầu");
    for (const label of [f.earlyInterestLabel, f.earlyForegoneLabel, f.earlyLossLabel]) expect(ex).toContain(`“${label}”`);
    const { html, caption } = pkg("tien-gui-co-ky-han");
    for (const s of ["27,5 triệu", "750 nghìn", "19,9 triệu"]) { expect(html).toContain(s); expect(caption).toContain(s); }
  });

  it("hưu trí: the route's own scenario, levers and suggestion", () => {
    const a = "de-danh-huu-tri-tien-du-den-bao-nhieu-tuoi";
    const run = (patch: Record<string, string> = {}) => resolveLongTermPlan(readRoutePlan({ ...RETIREMENT_PLAN.defaults, ...patch }).input!)!;
    const plan = run();
    const r = plan.asEntered;
    const first = r.years.find((y) => !y.accumulating)!;
    for (const n of [r.balanceAtRetirement, r.realBalanceAtRetirement, r.requiredRealBalanceAtRetirement, first.withdrawal]) expect(body(a)).toContain(vnd(n));
    expect([r.depletionAge, r.yearsFunded, r.yearsShort]).toEqual([75, 15, 10]);
    expect(Math.round(first.realWithdrawal)).toBe(48_000_000);
    // The year the savings run out is only partly paid: the poster's half-full bowl.
    expect(r.lastWithdrawalPaid! / r.lastWithdrawalPlanned!).toBeCloseTo(0.214, 2);
    const levers: [Record<string, string>, number, number][] = [
      [{ annualContribution: "27.000.000" }, 84, 1],
      [{ retirementAge: "61" }, 76, 9],
      [{ desiredMonthlySpending: "7.000.000" }, 80, 5],
    ];
    for (const [patch, age, short] of levers) {
      const x = run(patch).asEntered;
      expect([x.depletionAge, x.yearsShort], JSON.stringify(patch)).toEqual([age, short]);
    }
    const view = targetView(plan, retirementStatus(plan));
    expect(view.apply?.next).toBe("27.600.000");
    expect(view.share).toBe(60);
    const tried = run({ annualContribution: view.apply!.next }).asEntered;
    expect(tried.yearsShort).toBe(0);
    const H = RETIREMENT_PLAN.hero;
    const ex = exercise(a);
    for (const label of [H.figure.label, H.levers.annualContribution.up, H.levers.annualContribution.down, H.target.title, H.target.apply, H.target.undo, H.levers.retirementAge.up, H.levers.desiredMonthlySpending.down]) {
      expect(ex, label).toContain(named(label));
    }
    // Other income is an example, never an entitlement; returns are not guaranteed.
    expect(body(a)).toContain("không phải mức lương hưu BHXH bạn chắc chắn được nhận");
    const { html, caption } = pkg("ke-hoach-huu-tri");
    for (const s of ["2,2 tỷ", "730 triệu"]) { expect(html).toContain(s); expect(caption).toContain(s); }
    for (const age of [75, 84]) {
      for (const text of [html, caption]) expect(text).toMatch(new RegExp(`${age} tuổi|tuổi ${age}`));
    }
    expect(html.match(/class="bowl"/g)?.length).toBe(25);
  });

  it("phần trăm: 7% lên 9% in the “So hai mức lãi suất” mode", () => {
    const a = "lai-tu-7-len-9-tang-2-hay-28-phan-tram";
    const m = PERCENT.form.modes.points;
    expect([m.defaultA, m.defaultB]).toEqual(["7", "9"]);
    const r = computePercent({ mode: "points", a: 7, b: 9 });
    expect(r).toMatchObject({ differencePoints: 2 });
    const values = { mode: "points", pointsFrom: "7", pointsTo: "9" };
    const next = nextPercentValue("pointsTo", values)!;
    const after = percentFormState({ ...values, pointsTo: next }).result as { differencePoints: number; relativePercent: number };
    expect(next).toBe("10");
    expect(after.differencePoints).toBe(3);
    for (const s of [pct((r as { relativePercent: number }).relativePercent), pct(after.relativePercent)]) expect(body(a)).toContain(s);
    const ex = exercise(a);
    for (const label of [m.label, TOOL_SHELL.cta.label, PERCENT_LEARNING.title, PERCENT_LEARNING.trials.pointsTo.label, ARITH_WORDS.undo]) expect(ex, label).toContain(named(label));
    const { html, caption } = pkg("tinh-phan-tram");
    for (const s of ["2 điểm phần trăm", "28,57%"]) { expect(html).toContain(s); expect(caption).toContain(s); }
    expect(html).toContain("42,86%");
  });

  it("giảm giá: 1.000.000 ₫ đã gồm thuế, 20% rồi 10%, thuế 8%", () => {
    const a = "giam-20-roi-giam-10-co-phai-giam-30";
    const f = PRICE_ADJUST.form;
    const values = { price: f.defaultPrice, tax: f.defaultTax, taxIncluded: f.defaultTaxIncluded, discountPercent: f.defaultDiscountPercent, secondDiscountPercent: f.defaultSecondDiscountPercent, discountAmount: f.defaultDiscountAmount };
    expect(values).toEqual({ price: "1.000.000", tax: "8", taxIncluded: "yes", discountPercent: "20", secondDiscountPercent: "10", discountAmount: "0" });
    const base = adjustPrice({ listPrice: 1e6, discountPercent: 20, secondDiscountPercent: 10, discountAmount: 0, taxPercent: 8, taxIncluded: true })!;
    expect(base.finalPrice).toBe(720_000);
    expect(Math.round(base.combinedDiscountPercent)).toBe(28);
    for (const n of [base.finalPrice, base.firstPercentOff, base.secondPercentOff, base.tax, base.netPrice]) expect(body(a)).toContain(vnd(n).replace(" ₫", ""));
    const excluded = priceAdjustFormState({ ...values, taxIncluded: nextPriceValue("taxIncluded", values)! }).result!;
    const second = priceAdjustFormState({ ...values, secondDiscountPercent: nextPriceValue("secondDiscountPercent", values)! }).result!;
    expect(excluded.finalPrice).toBe(777_600);
    expect(second.finalPrice).toBe(680_000);
    expect(Math.round(second.combinedDiscountPercent)).toBe(32);
    for (const n of [excluded.finalPrice, excluded.tax, second.finalPrice]) expect(body(a)).toContain(vnd(n));
    const L = PRICE_ADJUST_LEARNING;
    const ex = exercise(a);
    for (const label of [TOOL_SHELL.cta.label, L.title, L.trials.secondDiscountPercent.label, L.trials.taxIncluded.label, ARITH_WORDS.undo]) expect(ex, label).toContain(named(label));
    const { html, caption } = pkg("giam-gia-va-thue");
    for (const s of ["720 nghìn", "777.600 ₫", "28%"]) { expect(html).toContain(s); expect(caption).toContain(s); }
  });

  it("margin: giá vốn 600.000 ₫, giá bán 1.000.000 ₫", () => {
    const a = "cong-40-vao-gia-von-co-phai-lai-40";
    const f = MARGIN.form;
    expect([f.defaultMode, f.defaultCost, f.defaultPrice]).toEqual(["price", "600.000", "1.000.000"]);
    const base = computeMargin({ mode: "price", cost: 600_000, value: 1_000_000 })!;
    const naive = computeMargin({ mode: "markup", cost: 600_000, value: 40 })!;
    const target = computeMargin({ mode: "margin", cost: 600_000, value: 40 })!;
    expect([base.profit, base.marginPercent, pct(base.markupPercent)]).toEqual([400_000, 40, "66,67"]);
    expect([naive.price, naive.profit, pct(naive.marginPercent)]).toEqual([840_000, 240_000, "28,57"]);
    expect(Math.round(target.price)).toBe(1_000_000);
    const values = { mode: "price", cost: f.defaultCost, price: f.defaultPrice, margin: f.defaultMargin, markup: f.defaultMarkup };
    expect(marginTrialKeys("price")).toContain("cost");
    const cost = marginFormState({ ...values, cost: nextMarginValue("cost", values)! }).result!;
    expect([cost.cost, cost.profit, cost.marginPercent, pct(cost.markupPercent)]).toEqual([660_000, 340_000, 34, "51,52"]);
    for (const s of [vnd(base.profit), vnd(naive.price), vnd(naive.profit), vnd(cost.profit), "66,67%", "28,57%", "51,52%"]) expect(body(a)).toContain(s);
    const ex = exercise(a);
    for (const label of [TOOL_SHELL.cta.label, MARGIN_LEARNING.title, MARGIN_LEARNING.trials.cost.label, ARITH_WORDS.undo, f.modeMarkup, f.modeMargin]) expect(ex, label).toContain(named(label));
    expect(body(a)).toContain("lợi nhuận gộp");
    const { html, caption } = pkg("margin-va-markup");
    for (const s of ["840 nghìn", "28,57%", "1 triệu"]) { expect(html).toContain(s); expect(caption).toContain(s); }
  });
});

describe("reused articles keep their declared household; posters quote it", () => {
  // The article objects are already pinned to their engines by the education
  // suites (approved-tool-guides, articles). Here the poster must agree with them.
  const cases: [string, string[]][] = [
    ["kha-nang-mua-nha", ["13 triệu", "1,94 tỷ", "100 triệu"]],
    ["vay-mua-nha", ["17,4 triệu", "19,4 triệu"]],
    ["lai-suat-tha-noi", ["16,11", "20,48", "2,48 triệu"]],
    ["muc-tieu-tiet-kiem", ["9,7 triệu", "11,1 triệu", "51,9 triệu"]],
  ];
  for (const [tool, figures] of cases) {
    it(`${tool}: every poster figure is in the article`, () => {
      const article = JSON.stringify(getEducationArticle(entry(tool).article));
      const { html, caption } = pkg(tool);
      for (const s of figures) {
        expect(article, s).toContain(s);
        expect(html, s).toContain(s);
        expect(caption, s).toContain(s);
      }
    });
  }
});

describe("social packages", () => {
  const fonts = ["diaVJ9Gu2AtlbsQszEnmsxwlIY.woff2", "u4FXY2bqWyT9VTGHSZbId85fOAk.woff2"];

  it("share one stylesheet with the original logo and Maison fonts, and a readiness signal", () => {
    const css = read("public/social/poster.css");
    for (const font of fonts) {
      expect(css).toContain(`../fonts/${font}`);
      expect(read("app/fonts.css")).toContain(font);
      expect(existsSync(`public/fonts/${font}`)).toBe(true);
    }
    expect(css).toContain("#117f36");
    const js = read("public/social/poster.js");
    for (const s of ["renderReady", "imagesReady", "brandFonts", "decode()", '"cover"', '"flow"']) expect(js).toContain(s);
  });

  for (const e of TOOL_EDUCATION_SERIES) {
    it(`${e.tool}: poster HTML and captions link the canonical article and tool, and state the assumption`, () => {
      const { html, caption } = pkg(e.tool);
      const article = `${SITE}/blog/${e.article}/`;
      expect(html).toContain('href="../poster.css"');
      expect(html).toContain('src="../poster.js"');
      expect(html).toContain('src="../../logos/logo-finhome-group.svg"');
      expect(html).toContain(`href="${article}"`);
      expect(html).toContain('lang="vi"');
      expect(html).toContain('name="robots" content="noindex"');
      expect(html).toMatch(/giả định/);
      for (const [, src] of html.matchAll(/src="(\.\.\/\.\.\/[^"]+)"/g)) {
        expect(existsSync(`public/${src.replace("../../", "")}`), src).toBe(true);
      }
      // REAL PEOPLE, ASIAN BY SOURCE METADATA (2026-09-30 rule): exactly the
      // assigned approved photo, credited, labelled illustrative, in the hero.
      const photo = PHOTOS[HERO_PHOTO[e.tool]];
      const hero = html.slice(html.indexOf('<section class="hero'), html.indexOf("</section>", html.indexOf('<section class="hero')));
      expect(hero).toContain(`src="../../${photo.file.replace(/^public\//, "")}"`);
      expect(hero).toContain(`Ảnh minh họa: ${photo.name} / Pexels`);
      expect(hero).toMatch(/alt="[^"]*ảnh minh họa, không phải nhân vật của ví dụ"/);
      expect(html).toContain("Người trong ảnh không đại diện ví dụ");
      expect(caption).toContain(photo.url);
      expect(caption).toContain("https://www.pexels.com/license/");
      expect(caption).toContain(`Ảnh ${photo.name} / Pexels chỉ minh họa; người trong ảnh không đại diện ví dụ`);
      // No 3D illustration or number-only hero is left.
      for (const gone of ["images/tools/", "hero--art", "hero--type", 'class="big"', "art-panel"]) expect(html, gone).not.toContain(gone);
      // A new guide's package can render its cover and article diagram.
      if (e.kind === "new") expect(html).toContain('class="flow-chart"');
      for (const heading of ["# Caption chính — Facebook", "# Caption ngắn — Facebook / Zalo", "# LinkedIn", "# Alt text cho poster", "# Liên kết"]) {
        expect(caption, heading).toContain(heading);
      }
      expect(caption).toContain(article);
      expect(caption).toContain(`${SITE}/cong-cu/${e.tool}/`);
      expect(caption).toMatch(/giả định/);
      expect(caption).toContain("Chưa đăng lên tài khoản social");
      for (const text of [html, caption]) {
        // The ambiguous annuity wording fixed on the car poster stays out.
        expect(text).not.toContain("trả đều gốc và lãi");
        expect(text).not.toMatch(/chắc chắn có lãi|lợi nhuận đảm bảo|được duyệt vay|bùng nổ/i);
      }
    });
  }

  it("lists all ten packages plus the car package on /social/", () => {
    const index = read("public/social/index.html");
    for (const tool of [...TOOL_EDUCATION_SERIES.map((e) => e.tool), "vay-mua-xe"]) {
      expect(index, tool).toContain(`href="${tool}/index.html"`);
      expect(index, tool).toContain(`href="${tool}/caption.md"`);
      expect(existsSync(`public/social/${tool}/index.html`), tool).toBe(true);
    }
    for (const e of TOOL_EDUCATION_SERIES) expect(index, e.article).toContain(`href="/blog/${e.article}/"`);
    expect(index).toContain('name="robots" content="noindex"');
  });

  it("is a thumbnail grid: every card previews and downloads a PNG that exists", () => {
    const index = read("public/social/index.html");
    const cards = [...index.matchAll(/<li class="card" data-package="([a-z-]+)">([\s\S]*?)<\/li>/g)];
    // Wave 2 (2026-10-01) adds its two packages once their PNGs exist; they use
    // the user-approved AI illustrations, credited as such, not a Pexels photo.
    const wave2 = LOAN_DECISION_SERIES.filter((e) => !LOAN_DECISION_PENDING_EXPORTS.includes(e.tool)).map((e) => e.tool);
    expect(cards.map((c) => c[1]).sort()).toEqual([...TOOL_EDUCATION_SERIES.map((e) => e.tool), "vay-mua-xe", ...wave2].sort());
    for (const [, tool, card] of cards) {
      const png = `public/social/${tool}/poster.png`;
      expect(existsSync(png), png).toBe(true);
      expect(card).toContain(`<img src="${tool}/poster.png" width="1080" height="1350" loading="lazy"`);
      expect(card).toContain(`<a class="download" href="${tool}/poster.png" download>Tải PNG</a>`);
      if (wave2.includes(tool)) expect(card).toContain('<p class="credit">Ảnh minh họa AI</p>');
      else expect(card).toMatch(/Ảnh: .+ \/ Pexels/);
      expect(card).toContain(`href="/cong-cu/${tool}/"`);
      expect(existsSync(`app/cong-cu/${tool}/page.tsx`), tool).toBe(true);
      const article = card.match(/href="\/blog\/([a-z0-9-]+)\/"/)![1];
      expect(getPost(article), article).toBeDefined();
    }
    // "Ready" is claimed only for real files, once per card.
    expect(index.match(/PNG sẵn sàng tải/g)?.length).toBe(cards.length);
    // Responsive, self-contained, and no posting claim.
    expect(index).toContain("grid-template-columns:repeat(auto-fill,minmax(220px,1fr))");
    expect(index).toMatch(/@media \(max-width:520px\)/);
    expect(index).toContain("../logos/logo-finhome-group.svg");
    expect(index).not.toMatch(/<script|src="https?:|href="https?:\/\/(?!www\.finhome)/);
    expect(index).toContain("chưa đăng lên bất kỳ tài khoản social nào");
  });
});

describe("people-first social imagery (user rule, 2026-09-30)", () => {
  const jpegSize = (file: string) => {
    // Walk JPEG markers to the first SOF segment; no image library needed.
    const b = readFileSync(file);
    let i = 2;
    while (i < b.length) {
      const marker = b[i + 1];
      const length = b.readUInt16BE(i + 2);
      if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
        return { w: b.readUInt16BE(i + 7), h: b.readUInt16BE(i + 5) };
      }
      i += 2 + length;
    }
    throw new Error(`no SOF in ${file}`);
  };

  it("ships each approved photo as its unmodified original", () => {
    for (const [id, p] of Object.entries(PHOTOS)) {
      expect(existsSync(p.file), p.file).toBe(true);
      expect(jpegSize(p.file), id).toEqual(p.size);
    }
  });

  it("gives every topic a DIFFERENT source photograph, none shared with the car package", () => {
    const idsIn = (html: string) => {
      const hero = html.slice(html.indexOf('<section class="hero'), html.indexOf("</section>", html.indexOf('<section class="hero')));
      return [...hero.matchAll(/pexels-(\d+)-original\.jpg/g)].map((m) => m[1]);
    };
    const used = TOOL_EDUCATION_SERIES.map((e) => {
      const ids = idsIn(pkg(e.tool).html);
      expect(ids, e.tool).toEqual([HERO_PHOTO[e.tool]]);
      return ids[0];
    });
    expect(new Set(used).size).toBe(10);
    const car = idsIn(read("public/social/vay-mua-xe/index.html"));
    expect(car).toEqual(["7593053"]);
    for (const id of car) expect(used, `series reuses the car photo ${id}`).not.toContain(id);
    // Nor anywhere else in the series' packages or guides: no stale credit.
    for (const e of TOOL_EDUCATION_SERIES) {
      for (const text of [pkg(e.tool).html, pkg(e.tool).caption, ...(e.kind === "new" ? [body(e.article)] : [])]) {
        expect(text, e.tool).not.toMatch(/7593053|Miriam Alonso/);
      }
    }
    // The released car package itself is untouched by this series.
    expect(read("public/social/vay-mua-xe/index.html")).not.toContain("../poster.css");
  });

  it("keeps faces clear of the headline wash in poster and cover, mirroring only text-free frames", () => {
    // Faces' left edge in DISPLAY units of the reviewed preview (long side 2000),
    // mirrored where the poster mirrors. The wash is transparent from 62% of the
    // hero width: poster box x ≥ 270 of 680, cover box x ≥ 334 of 790.
    const FACE_LEFT: Partial<Record<keyof typeof PHOTOS, number>> = {
      "7417519": 940, "7671364": 950, "8297072": 690, "7490459": 1000, "6545334": 860, "5154348": 580, "6538435": 770,
    };
    for (const [tool, id] of Object.entries(HERO_PHOTO)) {
      const html = pkg(tool).html;
      const img = html.match(new RegExp(`<img([^>]*)src="\\.\\./\\.\\./images/people/pexels-${id}-original\\.jpg"([^>]*)>`))!;
      const attrs = img[1] + img[2];
      expect(attrs.includes('class="flip"'), `${tool} mirroring`).toBe(MIRRORED.has(id));
      const left = FACE_LEFT[id];
      if (left === undefined) continue;
      const displayW = PHOTOS[id].size.w >= PHOTOS[id].size.h ? 2000 : Math.round((2000 * PHOTOS[id].size.w) / PHOTOS[id].size.h);
      const v = (name: string) => Number(attrs.match(new RegExp(`--${name}:(-?[\\d.]+)px`))![1]);
      for (const [w, x, clear] of [[v("w"), v("x"), 270], [v("cw"), v("cx"), 334]] as const) {
        const faceX = x + (left * w) / displayW;
        expect(faceX, `${tool} face at ${faceX}px`).toBeGreaterThanOrEqual(clear - 2);
      }
    }
  });

  it("keeps the compound diagram proportional and every part labelled outside the narrow segment", () => {
    const html = pkg("lai-kep").html;
    const flow = html.slice(html.indexOf('class="flow-chart"'), html.indexOf("</section>", html.indexOf('class="flow-chart"')));
    const bar = flow.match(/<div class="bar"[^>]*>([\s\S]*?)<\/div>/)![1];
    expect([...bar.matchAll(/flex:(\d+)/g)].map((m) => Number(m[1]))).toEqual([100, 960, 433]);
    expect(bar).toMatch(/<span style="flex:100"><\/span>/);
    expect(flow).toContain("Ban đầu 100 triệu");
    expect(flow).toContain("Gửi thêm 960 triệu");
    expect(flow).toContain("≈433 triệu");
    expect(flow).not.toContain("100tr");
  });

  it("never shows the printed word on the shirt in Pexels 7937885 (poster and cover)", () => {
    const html = read("public/social/ke-hoach-huu-tri/index.html");
    const style = html.match(/pexels-7937885-original\.jpg" style="([^"]+)"/)![1];
    const v = (name: string) => Number(style.match(new RegExp(`--${name}:(-?[\\d.]+)px`))![1]);
    // Source 3456 × 5184. The print's top edge measured at y ≈ 2943 in the source.
    const PRINT_TOP = 2943;
    for (const [w, y, boxH] of [[v("w"), v("y"), 445], [v("cw"), v("cy"), 520]] as const) {
      const scale = w / 3456;
      const bottomInSource = (boxH - y) / scale;
      expect(bottomInSource).toBeLessThan(PRINT_TOP - 50);
      // Both faces (source y ≈ 1500–2600) stay inside the box.
      expect(-y / scale).toBeLessThan(1500);
      expect(bottomInSource).toBeGreaterThan(2600);
    }
    expect(html).not.toMatch(/7937885[^>]*scaleX\(-1\)/);
  });

  it("uses no excluded or AI-labelled image anywhere in the series", () => {
    const texts = [
      read("public/social/poster.css"),
      read("public/social/index.html"),
      ...TOOL_EDUCATION_SERIES.flatMap((e) => [pkg(e.tool).html, pkg(e.tool).caption]),
      ...TOOL_EDUCATION_SERIES.filter((e) => e.kind === "new").map((e) => body(e.article)),
    ];
    for (const text of texts) {
      for (const banned of ["6818113", "8374288", "8374269", "AI25"]) expect(text).not.toContain(banned);
    }
    expect(existsSync("public/images/people/pexels-6818113-original.jpg")).toBe(false);
  });

  it("credits the photo each new guide's cover is exported with", () => {
    for (const e of TOOL_EDUCATION_SERIES.filter((x) => x.kind === "new")) {
      const photo = PHOTOS[HERO_PHOTO[e.tool]];
      const b = body(e.article);
      expect(b, e.article).toContain(`*Ảnh bìa: [${photo.name} / Pexels](${photo.url})`);
      expect(b, e.article).toContain("Người trong ảnh chỉ minh họa");
    }
  });

  it("keeps the rule in the project's own editorial guidance", () => {
    const skill = read(".cursor/skills/seo-blog/SKILL.md");
    // A portable rule: no incident date in its heading (dates live in the recap).
    expect(skill).toContain("### Social imagery (FinHome publishing rule)\n");
    expect(skill).not.toMatch(/### Social imagery[^\n]*\d{4}/);
    expect(skill).toMatch(/real people/);
    expect(skill).toMatch(/source's own metadata/);
    expect(skill).toMatch(/never presented as a real person/);
    expect(skill).toMatch(/different source photograph/);
    expect(skill).toContain("**What checking guarantees.**");
    expect(skill).toContain("**What it does not guarantee.**");
    expect(skill).toMatch(/remain a human\s+editorial decision/);
  });
});

describe("editorial repairs from the independent review", () => {
  it("percent: does not endorse “tăng 2%”, and does not call rounded values exact", () => {
    const b = body("lai-tu-7-len-9-tang-2-hay-28-phan-tram");
    expect(b).not.toContain("Cả hai đều có thể đúng");
    expect(b).toContain("Gọi khoảng cách đó là “tăng 2%” thì chưa đúng");
    expect(b).not.toContain("Bảng phía trên giữ số chính xác");
    expect(b).toContain("làm tròn đến hai chữ số thập phân");
    expect(pkg("tinh-phan-tram").caption).not.toMatch(/Ai đúng\?|Cả hai, nếu/);
  });

  it("margin: rounding stated, not exactness", () => {
    expect(body("cong-40-vao-gia-von-co-phai-lai-40")).not.toContain("giữ số chính xác");
  });

  it("retirement: the later-retirement effect is literal and bound to this example", () => {
    const b = body("de-danh-huu-tri-tien-du-den-bao-nhieu-tuoi");
    expect(b).not.toContain("cùng dịch đi");
    expect(b).toContain("thêm một năm để dành và bớt một năm phải rút tiền");
    expect(b).toContain("không phải quy luật chung");
  });

  it("deposit: cites the official Công báo page and claims no full reading", () => {
    const b = body("can-tien-truoc-dao-han-mat-bao-nhieu-lai");
    expect(b).toContain("https://congbao.chinhphu.vn/van-ban/van-ban-hop-nhat-so-34-vbhn-nhnn-42871/52043.htm");
    expect(b).not.toContain("tai-ve-van-ban-so-34-vbhn-nhnn");
    expect(b).toContain("Toàn văn cập nhật chưa được đọc lại cho bài này");
  });
});

describe("exported images: pending until Codex renders them, then required", () => {
  const png = (file: string) => {
    const bytes = readFileSync(file);
    return { sig: bytes.subarray(0, 8).toString("hex"), w: bytes.readUInt32BE(16), h: bytes.readUInt32BE(20) };
  };

  it("keeps PENDING_EXPORTS honest in both directions", () => {
    for (const e of TOOL_EDUCATION_SERIES) {
      const files = [{ file: `public/social/${e.tool}/poster.png`, width: 1080, height: 1350 }, ...e.exports];
      if (PENDING_EXPORTS.includes(e.tool)) {
        // Listed as pending: nothing may have been added under that name yet.
        expect(existsSync(`public/social/${e.tool}/poster.png`), `${e.tool} is exported; remove it from PENDING_EXPORTS`).toBe(false);
        continue;
      }
      for (const f of files) {
        expect(existsSync(f.file), f.file).toBe(true);
        expect(png(f.file), f.file).toEqual({ sig: "89504e470d0a1a0a", w: f.width, h: f.height });
      }
    }
    expect(PENDING_EXPORTS.every((tool) => TOOL_EDUCATION_SERIES.some((e) => e.tool === tool))).toBe(true);
  });

  it("RELEASE: nothing is pending — every declared export exists", () => {
    expect(PENDING_EXPORTS).toEqual([]);
    const all = TOOL_EDUCATION_SERIES.flatMap((e) => [`public/social/${e.tool}/poster.png`, ...e.exports.map((x) => x.file)]);
    expect(all).toHaveLength(22);
    for (const f of all) expect(existsSync(f), f).toBe(true);
  });
});
