// AUTO-GENERATED by scripts/import-assets.mjs. Maps Framer base filename -> public path.
export const IMG: Record<string, string> = {
  "11KSGbIZoRSg4pjdnUoif6MKHI.svg": "/images/11KSGbIZoRSg4pjdnUoif6MKHI.svg",
  "1fbxcHz89ad5POZ78mpq622pwyI.png": "/images/1fbxcHz89ad5POZ78mpq622pwyI.png",
  "2rgZQTmXdtEu6UJwxuFHaDvptI.png": "/images/2rgZQTmXdtEu6UJwxuFHaDvptI.png",
  "4F8Fzhd4rrU9Yv83jWxZjg6pqLc.jpg": "/images/4F8Fzhd4rrU9Yv83jWxZjg6pqLc.jpg",
  "4RetLJhrrvKYh3oS3lO0wfJLayM.png": "/images/4RetLJhrrvKYh3oS3lO0wfJLayM.png",
  "5Q3gFip1lY8vWKmRLAHPnkJqAis.svg": "/images/5Q3gFip1lY8vWKmRLAHPnkJqAis.svg",
  "6hJrSISXOuw6XHbmBRCGFMIE78.png": "/images/6hJrSISXOuw6XHbmBRCGFMIE78.png",
  "6tTbkXggWgQCAJ4DO2QEdXXmgM.svg": "/images/6tTbkXggWgQCAJ4DO2QEdXXmgM.svg",
  "9DWQzTIfFOk6ZkCVfnfpg9Fnz5Q.svg": "/images/9DWQzTIfFOk6ZkCVfnfpg9Fnz5Q.svg",
  "9s4vQoO4B1yGmAja7Y9j3ldBNDU.svg": "/images/9s4vQoO4B1yGmAja7Y9j3ldBNDU.svg",
  "B7GALiuXQGI2Hn8DV3wZSvuKtq8.png": "/images/B7GALiuXQGI2Hn8DV3wZSvuKtq8.png",
  "CKU5fM0cAKas042ZkEiDFMZCCrU.jpg": "/images/CKU5fM0cAKas042ZkEiDFMZCCrU.jpg",
  "FdTECw5LUUzz9aOkP0KsSvHD0Y.png": "/images/FdTECw5LUUzz9aOkP0KsSvHD0Y.png",
  "IOcQQ3D0fTC4NO9ssmjNPnzroXQ.svg": "/images/IOcQQ3D0fTC4NO9ssmjNPnzroXQ.svg",
  "IYLfwxW8aq7NydpexjdGUDzyA.png": "/images/IYLfwxW8aq7NydpexjdGUDzyA.png",
  "J4egHxMXt0WzHvMHScZmhl6Dkc.png": "/images/J4egHxMXt0WzHvMHScZmhl6Dkc.png",
  "KUdQQxHfWk8dBDvdbyQ983ZcTI.png": "/images/KUdQQxHfWk8dBDvdbyQ983ZcTI.png",
  "KkQ6bZ6ezs4ASm9zGhCxZRRF1o.jpg": "/images/KkQ6bZ6ezs4ASm9zGhCxZRRF1o.jpg",
  "MvgTNGLn4lUKne928t46iiqxY.png": "/images/MvgTNGLn4lUKne928t46iiqxY.png",
  "PQLhDmvFrnxHe3GZoIseyfdJrrc.svg": "/images/PQLhDmvFrnxHe3GZoIseyfdJrrc.svg",
  "VnhOAfra6cWAj4k6aWSHjctp59o.png": "/images/VnhOAfra6cWAj4k6aWSHjctp59o.png",
  "W9DPNIyHaEmP2Cj7bG3UxiMbg.png": "/images/W9DPNIyHaEmP2Cj7bG3UxiMbg.png",
  "Ym3IuKDBwg0U6P3YdFiwaa2xKE.png": "/images/Ym3IuKDBwg0U6P3YdFiwaa2xKE.png",
  "ZYeE9HPY4yfLdeQA4G5HW49WveQ.svg": "/images/ZYeE9HPY4yfLdeQA4G5HW49WveQ.svg",
  "dTeZrxbqIYr4yq8uPXe5gxdbM.jpg": "/images/dTeZrxbqIYr4yq8uPXe5gxdbM.jpg",
  "hInhX9UgJBuGaSywFBNNbocS2t0.png": "/images/hInhX9UgJBuGaSywFBNNbocS2t0.png",
  "iFYY6KsVY4Sg2HETYv3vxfrz8.png": "/images/iFYY6KsVY4Sg2HETYv3vxfrz8.png",
  "jvkUqoHRnEVcOwyGhBPCxnUNU.png": "/images/jvkUqoHRnEVcOwyGhBPCxnUNU.png",
  "o8jJXgRiX6LN7LOGgMXmaxsupVs.png": "/images/o8jJXgRiX6LN7LOGgMXmaxsupVs.png",
  "oIxITa5snaVT7XXKnAxj031jsc.jpg": "/images/oIxITa5snaVT7XXKnAxj031jsc.jpg",
  "oWCUzm8toUrYjCtF86RIMXwJky8.jpg": "/images/oWCUzm8toUrYjCtF86RIMXwJky8.jpg",
  "pBWyVGbn6q90q7em1mpZCUhjo.jpg": "/images/pBWyVGbn6q90q7em1mpZCUhjo.jpg",
  "qiB3oKKzF4BijpvumvHCnb6KFvw.png": "/images/qiB3oKKzF4BijpvumvHCnb6KFvw.png",
  "qxo9XhPCBEGMBRbIAxUtPmW8bw.png": "/images/qxo9XhPCBEGMBRbIAxUtPmW8bw.png",
  "sS56Q5YGS57bP8Vlbh3A6HHVHDQ.jpg": "/images/sS56Q5YGS57bP8Vlbh3A6HHVHDQ.jpg",
  "snmk1qnjE3RS5mJGpYhdgBwvSI.jpg": "/images/snmk1qnjE3RS5mJGpYhdgBwvSI.jpg",
  "tpQ6tMpwmvmfHToJKBGPClPFTbU.png": "/images/tpQ6tMpwmvmfHToJKBGPClPFTbU.png",
  "wucS1gLE60ECBgA4gyzkB26d4.svg": "/images/wucS1gLE60ECBgA4gyzkB26d4.svg",
  "x8UhU3ZT5q88N36ilFB6B0Tu7kE.svg": "/images/x8UhU3ZT5q88N36ilFB6B0Tu7kE.svg",
  "y9hwKK3MJX6DL9OckY7P3La9kZg.svg": "/images/y9hwKK3MJX6DL9OckY7P3La9kZg.svg",
  "Z8KIqP7hqZvzaK06QSJARSULQQw.png": "/images/Z8KIqP7hqZvzaK06QSJARSULQQw.png",
  "zU4hhLtCQQrRV7D1ZZ3IKzyve2g.png": "/images/zU4hhLtCQQrRV7D1ZZ3IKzyve2g.png",
};

export function img(base: string): string {
  // Allow direct public paths (e.g. crawled blog covers under /images/blog/).
  if (base.startsWith("/")) return base;
  const p = IMG[base];
  if (!p) throw new Error(`Unknown image: ${base}`);
  return p;
}
