// Import assets from the Framer mirror into this Next.js app.
//  - images/* : weird wget names like "abc.png@scale-down-to=1024&width=...".
//    Keep the LARGEST variant per base name; copy to public/images/<base>.
//  - assets/*.woff2 : copy verbatim to public/fonts/.
//  - @font-face blocks (Inter + Maison Neue) in index.html: rewrite
//    url("assets/X.woff2") -> url("/fonts/X.woff2"); write app/fonts.css.
//  - emit lib/images.ts mapping originalBaseName -> "/images/<base>".
import fs from "node:fs";
import path from "node:path";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const APP = path.resolve(HERE, "..");
const MIRROR = path.resolve(APP, "..", "finhome-framer-mirror");

const pubImg = path.join(APP, "public", "images");
const pubFont = path.join(APP, "public", "fonts");
fs.mkdirSync(pubImg, { recursive: true });
fs.mkdirSync(pubFont, { recursive: true });

// ---- images: keep largest variant per base name ----
const srcImg = path.join(MIRROR, "images");
const best = new Map(); // base -> {file, size}
for (const name of fs.readdirSync(srcImg)) {
  const full = path.join(srcImg, name);
  if (!fs.statSync(full).isFile()) continue;
  const base = name.split("@")[0]; // strip @... suffix
  const size = fs.statSync(full).size;
  const cur = best.get(base);
  if (!cur || size > cur.size) best.set(base, { file: full, size });
}
const imageMap = {};
for (const [base, { file }] of best) {
  fs.copyFileSync(file, path.join(pubImg, base));
  imageMap[base] = `/images/${base}`;
}

// ---- fonts: copy every woff2 in assets/ ----
const srcAssets = path.join(MIRROR, "assets");
for (const name of fs.readdirSync(srcAssets)) {
  if (name.endsWith(".woff2")) {
    fs.copyFileSync(path.join(srcAssets, name), path.join(pubFont, name));
  }
}

// ---- extract @font-face blocks referencing assets/ ----
const html = fs.readFileSync(path.join(MIRROR, "index.html"), "utf8");
const faces = [];
const re = /@font-face\s*\{[^}]*\}/gs;
let m;
while ((m = re.exec(html))) {
  const block = m[0];
  if (block.includes("assets/")) {
    faces.push(block.replace(/url\(("?)assets\//g, 'url($1/fonts/'));
  }
}
const fontCss =
  "/* Generated by scripts/import-assets.mjs — local @font-face from Framer mirror */\n" +
  faces.join("\n") +
  "\n";
fs.writeFileSync(path.join(APP, "app", "fonts.css"), fontCss);

// ---- emit lib/images.ts ----
fs.mkdirSync(path.join(APP, "lib"), { recursive: true });
const entries = Object.keys(imageMap)
  .sort()
  .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(imageMap[k])},`)
  .join("\n");
const ts =
  "// AUTO-GENERATED by scripts/import-assets.mjs. Maps Framer base filename -> public path.\n" +
  "export const IMG: Record<string, string> = {\n" +
  entries +
  "\n};\n\n" +
  "export function img(base: string): string {\n" +
  "  const p = IMG[base];\n" +
  "  if (!p) throw new Error(`Unknown image: ${base}`);\n" +
  "  return p;\n}\n";
fs.writeFileSync(path.join(APP, "lib", "images.ts"), ts);

console.log(
  `images: ${Object.keys(imageMap).length}, fonts: ${
    fs.readdirSync(pubFont).length
  }, font-faces: ${faces.length}`
);
